# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

AcmeTomatomanBundle:
    resource: "@AcmeTomatomanBundle/Resources/config/routing.yml"
    prefix: /