homepage:
    pattern:  /
    defaults: { _controller: AcmeTomatomanBundle:Default:index }

login:
    pattern: /login
    defaults: { _controller: AcmeTomatomanBundle:Security:login }

login_check:
    pattern: /login_check
    
logout:
    pattern: /logout


admin_project_crud:    
    resource: "routing/project.yml"
    prefix: /admin/project