parameters:
#    acme_tomatoman.example.class: Acme\TomatomanBundle\Example

services:
#    acme_tomatoman.example:
#        class: %acme_tomatoman.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
